{
    'name': 'Product Configurator',
    'version': '11.0.2.16.9.2019',
    "sequence": 0,
    'category': 'Generic Modules/Base',
    'summary': 'Base for product configuration interface modules',
    'author': 'Kiran Kantesariya',
    'license': 'AGPL-3',
    'depends': ['account', 'website_sale_stock'],
    "data": [
        'data/menu_configurable_product.xml',
        'data/product_attribute.xml',
        'data/ir_sequence_data.xml',
        'data/menu_product.xml',
        'security/configurator_security.xml',
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/product_view.xml',
        'views/product_attribute_view.xml',
        'views/product_config_view.xml',
        'wizard/product_configurator_view.xml',
        'views/sale_view.xml',
        'views/stock_lot_view.xml',
    ],
    'demo': [
        # 'demo/product_template.xml',
        # 'demo/product_attribute.xml',
        # 'demo/product_config_domain.xml',
        # 'demo/product_config_lines.xml',
        # 'demo/product_config_step.xml',
        # 'demo/config_image_ids.xml',
    ],
    'images': [
        'static/description/icon.png'
    ],
    'qweb': ['static/xml/create_button.xml'],
    'test': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
